version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
ApplicationStart:
  - location: scripts/run_new_was.sh
    timeout: 60
    runas: ubuntu
  - location: scripts/health_check.sh
    timeout: 60
    runas: ubuntu
  - location: scripts/switch.sh
    timeout: 60
    runas: ubuntu

#--------------
#hooks:
#  AfterInstall:
#    - location: stop.sh # nginx와 연결되지 않은 스프링 부트 종료.
#      timeout: 60
#      runas: ubuntu
#  ApplicationStart:
#    - location: start.sh # nginx와 연결되어 있지 않은 포트로 스프링 부트 시작.
#      timeout: 60
#      runas: ubuntu
#  ValidateService:
#    - location: health.sh # 새 서비스 health check.
#      timeout: 60
#      runas: ubuntu