spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${mail.username} # 발신자
    password: ${mail.password} # 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부
          timeout: 5000 # Socket Read Timeout 시간(ms)
          starttls:
            enable: true # StartTLS 활성화 여부
  thymeleaf:
    cache: false
    prefix: classpath:/templates/